### ISSUE TITLE
Windows Portable crashes

### ISSUE THREAD

**Issue by Dante-7** [Issung/GChan#3]
I tested it with out of the box settings (+ Download html) and the https://boards.4channel.org/v/
It doenst give out a error message, just programm crashed. I cant change any settings, because it crashes asap after starting. 

<img width="277" alt="Screenshot_3" src="https://user-images.githubusercontent.com/69360528/89670065-da99ae00-d8e0-11ea-982c-4f450d3df6e5.png">

**Comment by Issung** [comment]
Hi there, thanks for reporting your issue!
This is probably a problem with scraping a board, which is a mostly untested feature at the moment. 
I will look into testing it more when I get the time and hopefully fix the issue, and will let you know.
Just for now I would really appreciate it if you could upload your crash logs to somewhere like pastebin and link it here, your crash logs can be found in a file called crash.logs at C:\ProgramData\GChan\GChan\3.3.0. 
After you have uploaded those and shared them here, delete all files in the directory (there should be crash.logs, boards.dat, and threads.dat, delete them all) and restart the program, it should then work, but be careful with adding boards again, maybe just stick to threads for the time being.

**Comment by Dante-7** [comment]
Hey, thanks for your fast reply! :) 
I tested the installer Version, but still havent a folder.
I found it under C:\User\AppData\Local\Apps\2.0\ with the help of the task manager

Anyway, I tryd the same board url again, this time without html, and it crashes again.
But no crash logs. Same with the portable.

<img width="603" alt="Screenshot_1" src="https://user-images.githubusercontent.com/69360528/89708665-3dd71f00-d979-11ea-96d4-ec36bc2b8ec6.png">

**Comment by Issung** [comment]
Hi again, what you've found is the install directory, it is a different directory to where it stores the data and crash logs. For the portable version it should be at "C:\ProgramData\GChan\GChan\3.3.0" or somewhere similar, try accessing the path directly because Windows hides the ProgramData folder by default.
This is what it should look like in the folder:
![image](https://user-images.githubusercontent.com/22212465/89708912-587fb700-d9be-11ea-80f8-e1ebec3e3413.png)"

If you use the installer version it gets stored somewhere stupid, in my case it gets stored here "C:\Users\username\AppData\Local\Apps\2.0\Data\G9Q5N6L8.T90\T00CKN0M.PGZ\gcha..tion_2cfeb7be995d8803_0002.0007_6d1fe2d8e26d6fe8\Data".

Maybe you can find it by going to your local AppData folder and searching for "crash.logs" or something.

If you manage to open GChan you can actually open the folder with the "Open ProgramData Folder" button. 
![image](https://user-images.githubusercontent.com/22212465/89708948-b6140380-d9be-11ea-87ff-d8333e4145e8.png)

**Comment by Issung** [comment]
About the crashing: I think it is probably crashing because /v/ is a very popular board and its probably freaking out about all the movement... But I will need your crash.logs and some testing once I have time to find the true cause. I only scrape individual threads of my choosing so I haven't had this issue, but I will try and fix it once I get a chance.

**Comment by Dante-7** [comment]
So, sorry for my stupid mistake, you was right, it was hidden.

https://pastebin.com/raw/UFhukfbB (crash.logs)

**Comment by Issung** [comment]
Hi friend, I've made a quick patch that should hopefully fix this issue for you, please download it from the releases here: https://github.com/Issung/GChan/releases/tag/3.3.2

And let me know if it works out for you :)

**Comment by Dante-7** [comment]
Hey again, thanks for the very fast patch.
I tested the portabl eagain, this time with html too, 
and it works like a charm, thank you! :)
<img width="485" alt="Screenshot_3" src="https://user-images.githubusercontent.com/69360528/89741488-01e3ad00-da92-11ea-9937-ed6903281b56.png">
