### ISSUE TITLE
URL list not saving on closing and thread list info not updating until getting clicked and scrolling issue

### ISSUE THREAD

**Issue by 1024mb** [Issung/GChan#8]
Title is self-explanatory, the URLs aren't saved when GChan exits with the appropriated option ticked.  
Also the thread list doesn't updates itself until I click each thread. So if I add several threads appended with a comma they are all added to the queue but all stay at FileCount 0 until I click them, then it reloads.

Edit: Something more I was forgetting about, when the queue is long enough there is no scrollbar and it can't be scrolled with the mouse wheel either. It can be scrolled with the keyboard arrows though.

First time using this app so sorry if these are known problems, and thanks, it works great.

**Comment by Issung** [comment]
Hi 1024mb, glad to hear you are enjoying the application, but also sorry for the errors.

As for the errors:
1. Threads/Boards URLs not saving: I've had no problems with this and no reports of it either, it saves the information into files and problems can often arise with this due to user permissions and things like that, please check the logs file in the ProgramData directory (open GChan and go File -> Open ProgramData Folder) and see if there is any useful information in there, if you don't understand any of it please go ahead and dump it all in pastebin or something.
2. FileCount not updating: Yes this is known about, mostly due to me being lazy and only just starting to use DataBinding recently, I am to fix this in a nearby release.
3. ScrollBar not appearing, this one is unknown to me, perhaps the logs file can provide more information about this, or yourself describing a way to recreate the behaviour? 

Thanks for your issue reports, they help make GChan a better program.

**Comment by 1024mb** [comment]
I don't know what I did or I haven't done but after closing and opening GChan again it saved the queue and also I'm able to see the scrollbar and use the mouse wheel. That's weird. Maybe it only happens on the first opening of the app when is installed for the first time? I mean, that's the only explanation I can find. All I did was install the app, configure it, add some threads, close it and reopen it.

> FileCount not updating: Yes this is known about, mostly due to me being lazy and only just starting to use DataBinding recently, I am to fix this in a nearby release.

No problem, is not a big issue. Glad to see you are actively working on the app. Thanks.

**Comment by Issung** [comment]
I found some possible causes for these issues tonight and fixed them, have also fixed the automatic updating file counts without the need to manual "update" them by clicking on/off them. These fixes will be pushed in the next release. Thank you.
